spring:
  profiles:
    active: local
  application:
    name: chatting-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

server:
  port: 9000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secret-key: secret-key-one-two-dear-my-x-it-will-be-change-next-time

access-id: server-access-id
access-key: server-access-key

mailbox-auto-config:
  option: "on"
  access-key-check: "false"
  logging: "on"
  security: "on"

grpc:
  client:
    user:
      address: 'static://127.0.0.1:9090'
      negotiation-type: plaintext

---

spring:
  config:
    activate:
      on-profile: dev